# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master, next/* ]
  pull_request:
    branches: [ master, next/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: ShadowJar modget-create-core
      run: ./gradlew :modget-create-core:shadowJar
    - name: ShadowJar modget-create-cli
      run: ./gradlew :modget-create-cli:shadowJar
    - name: Upload modget-create-cli
      uses: actions/upload-artifact@v3
      with:
        name: modget-create-cli-dev
        path: modget-create-cli/build/libs/*.jar

